version: "3"

services:
    db: 
        image: postgres
        restart: always
        environment:
           POSTGRES_PASSWORD: root

    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        container_name: node-container
        command: yarn dev
        volumes:
            - ./server:/usr/app
        ports:
            - "3333:3333"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        command: yarn start
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/usr/app
        stdin_open: true